import { Product } from "../interfaces/model.interface";

const products: Product[] = [
  {
    id: 1,
    name: "Coca Cola",
    volume: 0.5,
    price: 10000,
    cost: 5000,
    unit: "lon",
    type: "soft drink",
    size: 1,
  },
  {
    id: 2,
    name: "Pepsi",
    volume: 0.5,
    price: 10000,
    cost: 5000,
    unit: "lon",
    type: "soft drink",
    size: 1,
  },
  {
    id: 3,
    name: "Sting",
    volume: 0.5,
    price: 10000,
    cost: 5000,
    unit: "lon",
    type: "soft drink",
    size: 1,
  },
  {
    id: 4,
    name: "Red Bull",
    volume: 0.5,
    price: 10000,
    cost: 5000,
    unit: "lon",
    type: "soft drink",
    size: 1,
  },
  {
    id: 5,
    name: "Number One",
    volume: 0.5,
    price: 10000,
    cost: 5000,
    unit: "lon",
    type: "soft drink",
    size: 1,
  },
  {
    id: 6,
    name: "Aquafina",
    volume: 0.5,
    price: 10000,
    cost: 5000,
    unit: "lon",
    type: "soft drink",
    size: 1,
  },
  {
    id: 7,
    name: "Sting",
    volume: 0.5,
    price: 10000,
    cost: 5000,
    unit: "lon",
    type: "soft drink",
    size: 1,
  },
  {
    id: 8,
    name: "Red Bull",
    volume: 0.5,
    price: 10000,
    cost: 5000,
    unit: "lon",
    type: "soft drink",
    size: 1,
  },
];
export default products;
