EXEC create_chat 'Vos damnatio attonbitus stipes conicio tabernus volup allatus abstergo.', 2, 1;
EXEC create_chat 'Congregatio coaegresco deputo alienus colo calculus.', 3, 6;
EXEC create_chat 'Clam molestias consuasor candidus coruscus fugiat aptus copia.', 1, 1;
EXEC create_chat 'Cattus cito amor.', 8, 7;
EXEC create_chat 'Conspergo aranea totus atrocitas cruentus circumvenio sto labore.', 7, 6;
EXEC create_chat 'Contigo verecundia vos strues error.', 5, 10;
EXEC create_chat 'Antea traho trucido.', 10, 6;
EXEC create_chat 'Vomito vindico ceno adamo currus confugo depereo.', 6, 2;
EXEC create_chat 'Doloribus acsi sublime tendo crux carbo ultio.', 5, 3;
EXEC create_chat 'Rerum tabula cui turba acidus surculus defetiscor appositus talio vae.', 8, 10;
EXEC create_chat 'Adipiscor suscipit aperio callide decerno talio ventus aestus colligo alienus.', 7, 8;
EXEC create_chat 'Communis tepesco demum talio causa tredecim cum.', 2, 8;
EXEC create_chat 'Charisma tabernus creator adipiscor sopor suppono cubo tribuo vetus eius.', 4, 7;
EXEC create_chat 'Utpote concido nobis aspernatur commodi sapiente voluptate umquam.', 1, 3;
EXEC create_chat 'Audax suffoco vae undique carpo tonsor.', 1, 7;
EXEC create_chat 'Non tunc adnuo tres.', 5, 4;
EXEC create_chat 'Contego angustus colo convoco unus valeo accommodo dicta.', 5, 2;
EXEC create_chat 'Tabula caute carcer quibusdam pauci turpis.', 2, 10;
EXEC create_chat 'Vero facere crux adhaero temeritas sopor sponte recusandae tamisium.', 3, 1;
EXEC create_chat 'Admoveo culpa verumtamen creta carmen tricesimus xiphias tunc timidus strenuus.', 1, 3;
EXEC create_chat 'Suppono suasoria velit tenuis succurro arbor.', 2, 4;
EXEC create_chat 'Vulgo adinventitias cito temptatio decimus coniuratio inflammatio traho.', 5, 4;
EXEC create_chat 'Talus cohibeo pauci somniculosus dolorum laborum summisse contigo.', 6, 9;
EXEC create_chat 'Iste audax illo centum conspergo eveniet ait sub.', 4, 4;
EXEC create_chat 'Tricesimus delinquo patrocinor similique praesentium audax admitto decumbo coepi.', 7, 2;
EXEC create_chat 'Praesentium vapulus utrimque sponte teneo.', 4, 10;
EXEC create_chat 'Acies aperte appono facilis umbra.', 9, 6;
EXEC create_chat 'Coepi fugiat defessus advenio amor accusantium coma.', 10, 1;
EXEC create_chat 'Conculco terror eaque dolores concedo turpis asperiores illum.', 4, 6;
EXEC create_chat 'Atavus cubitum advenio degusto ventosus totidem calco.', 1, 5;
EXEC create_chat 'Acsi vis dolor decet.', 9, 1;
EXEC create_chat 'Vergo terra verto.', 2, 3;
EXEC create_chat 'Decumbo venio viscus carmen soluta barba pectus vespillo.', 6, 5;
EXEC create_chat 'Theatrum umerus curvo torrens averto temporibus.', 3, 2;
EXEC create_chat 'Omnis maxime atque.', 10, 7;
EXEC create_chat 'Soleo concido subnecto averto compono convoco tametsi curia candidus capio.', 10, 10;
EXEC create_chat 'Utor tondeo aer vita auditor sub atque cauda caecus.', 10, 4;
EXEC create_chat 'Desolo allatus vehemens expedita deporto cupiditate curo.', 8, 3;
EXEC create_chat 'Expedita acervus suscipio.', 2, 6;
EXEC create_chat 'Talis commodo sub cauda vaco tolero tabernus creo via.', 9, 9;
EXEC create_chat 'Substantia versus speculum trado calculus stella.', 1, 8;
EXEC create_chat 'Derideo casso tui xiphias caecus aequitas adopto veritatis.', 3, 10;
EXEC create_chat 'Tolero universe maiores creo.', 4, 9;
EXEC create_chat 'Clam decipio error calcar thema desparatus temeritas quisquam constans strues.', 5, 3;
EXEC create_chat 'Ceno tracto aliquam succurro dapifer caterva collum arbustum absum infit.', 6, 9;
EXEC create_chat 'Cunae taedium cauda cupio ago summa ultra recusandae attonbitus utroque.', 1, 1;
EXEC create_chat 'Sodalitas tam apto creo stipes cruciamentum quos totus itaque corrigo.', 10, 6;
EXEC create_chat 'Defaeco carus causa demulceo.', 2, 1;
EXEC create_chat 'Armarium amitto possimus modi statua ventus usque sint solio.', 7, 10;
EXEC create_chat 'Coaegresco tabula bos minima supra.', 4, 4;
EXEC create_chat 'Xiphias campana aestas ademptio vel amplus termes comprehendo animi.', 8, 4;
EXEC create_chat 'Careo soluta uredo.', 5, 8;
EXEC create_chat 'Aequus ipsam cresco catena infit provident tego.', 3, 6;
EXEC create_chat 'Trado ventosus verto tergo depono clarus.', 5, 5;
EXEC create_chat 'Artificiose cursus deprecator sto caveo abstergo laborum vulgaris adipiscor.', 9, 4;
EXEC create_chat 'Adfectus arguo coniecto aiunt tolero spargo.', 4, 9;
EXEC create_chat 'Administratio ullam crapula verumtamen.', 9, 9;
EXEC create_chat 'Adstringo decet clibanus bellicus libero vesica deripio charisma.', 2, 8;
EXEC create_chat 'Cruentus confero admitto supra aliqua subito confero vespillo ventosus.', 5, 4;
EXEC create_chat 'Valde aliqua vilitas bene virtus auctor cruentus cunctatio.', 3, 3;
EXEC create_chat 'Appono debeo coaegresco volaticus.', 7, 10;
EXEC create_chat 'Totam delectatio verumtamen causa usque denego patruus consequuntur.', 9, 7;
EXEC create_chat 'Somniculosus vis contra solvo bis decet textilis toties demoror creber.', 9, 8;
EXEC create_chat 'Verbum paulatim terminatio consequatur strues degenero tero.', 4, 9;
EXEC create_chat 'Strues vicissitudo crustulum causa.', 5, 5;
EXEC create_chat 'Magnam congregatio cariosus doloribus vox armarium voro absens curto dedecor.', 2, 5;
EXEC create_chat 'Synagoga copiose abstergo culpo abbas subnecto tempus beatus.', 2, 2;
EXEC create_chat 'Arcus verus tumultus theatrum verus advoco tantum vapulus substantia.', 6, 1;
EXEC create_chat 'Calco vergo tripudio damno adiuvo crepusculum antiquus voluptates capitulus.', 5, 2;
EXEC create_chat 'Aegrus curiositas terreo modi aestus perspiciatis voluptatem.', 3, 2;
EXEC create_chat 'Calcar ago quod acervus suadeo solio capillus sodalitas.', 5, 7;
EXEC create_chat 'Absque usitas tergeo contego absconditus amissio virgo deduco.', 1, 1;
EXEC create_chat 'Vos placeat trado.', 5, 6;
EXEC create_chat 'Curriculum denique pauci.', 2, 8;
EXEC create_chat 'Caritas quae defendo.', 9, 4;
EXEC create_chat 'Comis delectatio subseco tepesco cauda ager supra.', 4, 5;
EXEC create_chat 'Paulatim eaque suppellex pauci careo.', 1, 9;
EXEC create_chat 'Patria baiulus ante teneo placeat sunt custodia tutis timidus.', 7, 1;
EXEC create_chat 'Celebrer talis dens curto textilis asperiores.', 1, 10;
EXEC create_chat 'Voluptatibus crapula adipisci itaque aer vigor deduco defendo enim cupiditas.', 2, 7;
EXEC create_chat 'Desolo virtus facilis tendo acervus uter.', 8, 4;
EXEC create_chat 'Textor iste adaugeo charisma cernuus accedo tersus vilicus vobis cupiditate.', 4, 9;
EXEC create_chat 'Conventus suffoco vitae tempore accusamus vita sonitus.', 6, 5;
EXEC create_chat 'Arto demulceo ultio tui contra vinum voluptatem.', 2, 10;
EXEC create_chat 'Creator vita autem.', 6, 6;
EXEC create_chat 'Addo undique crastinus coniecto comburo aestivus voluptatum usque peccatus dolor.', 1, 4;
EXEC create_chat 'Accusantium turbo vetus modi denuncio cogo.', 1, 10;
EXEC create_chat 'Caelestis adficio turba arma earum theatrum cognatus.', 6, 7;
EXEC create_chat 'Consuasor degenero valde termes commodi sursum.', 3, 8;
EXEC create_chat 'Provident calco delibero quos uter cinis nobis templum iure.', 4, 5;
EXEC create_chat 'Unus aspicio inventore vulpes amaritudo subseco absum.', 2, 5;
EXEC create_chat 'Statua minima sub defaeco aequitas.', 10, 10;
EXEC create_chat 'Caelum thalassinus caput accusamus tres repudiandae ipsa textor.', 6, 1;
EXEC create_chat 'Architecto cogo antiquus pecto volutabrum sonitus virtus praesentium.', 6, 7;
EXEC create_chat 'Avarus vigilo umerus spiculum vigor iste tenuis nobis volup.', 7, 10;
EXEC create_chat 'Vel super coniuratio statim molestias ceno iste delego delectatio reprehenderit.', 8, 2;
EXEC create_chat 'Vomica calamitas quas reiciendis beatus.', 5, 10;
EXEC create_chat 'Civitas supra custodia cena modi aiunt.', 9, 3;
EXEC create_chat 'Adimpleo atrocitas aro talio.', 10, 9;
EXEC create_chat 'Animi solus adeo argentum minus.', 9, 7;