EXEC create_message_forum 'Admiratio ad acidus cohaero.', 5, 4;
EXEC create_message_forum 'Denuo cetera ad alveus cedo subiungo theca comparo suffragium bestia.', 2, 9;
EXEC create_message_forum 'Cruciamentum casus acer eum abutor suadeo libero.', 10, 4;
EXEC create_message_forum 'Thalassinus deputo ars tredecim quo decretum careo.', 1, 7;
EXEC create_message_forum 'Varietas vesco voluptates via.', 2, 1;
EXEC create_message_forum 'Quasi avaritia cupressus tristis comburo.', 2, 10;
EXEC create_message_forum 'Assentator caute subseco.', 6, 5;
EXEC create_message_forum 'Balbus aetas acies pectus cognomen demitto tener conspergo.', 3, 4;
EXEC create_message_forum 'Verus solio absorbeo video ascit.', 10, 7;
EXEC create_message_forum 'Speculum eius socius ventosus strenuus.', 3, 10;
EXEC create_message_forum 'Natus spes socius approbo aestus quisquam.', 1, 7;
EXEC create_message_forum 'Vere tristis assumenda texo strues argumentum voluptate vigor.', 3, 3;
EXEC create_message_forum 'Vulgaris substantia adaugeo vobis dapifer adsidue vitiosus colligo circumvenio.', 5, 6;
EXEC create_message_forum 'Repellat supplanto substantia viduo aurum incidunt tergo.', 6, 4;
EXEC create_message_forum 'Vitium arbitro sperno contigo cursim conitor thorax causa surgo dolor.', 3, 8;
EXEC create_message_forum 'Charisma suus sum.', 5, 5;
EXEC create_message_forum 'Sollers tametsi caterva venustas pauper illo super.', 4, 1;
EXEC create_message_forum 'Carpo crudelis vicinus culpo sordeo timidus cilicium alter beatae.', 8, 2;
EXEC create_message_forum 'Odit complectus culpa.', 3, 8;
EXEC create_message_forum 'Thermae vulnus tepesco patruus decumbo urbs totidem terror vado.', 3, 4;
EXEC create_message_forum 'Suggero theca caute cimentarius decipio explicabo.', 9, 9;
EXEC create_message_forum 'Depraedor caelestis degero dolore.', 7, 1;
EXEC create_message_forum 'Congregatio sublime templum adficio appono aufero.', 4, 4;
EXEC create_message_forum 'Cupio nobis volutabrum canonicus tendo degenero.', 3, 9;
EXEC create_message_forum 'Deporto desipio sint cariosus.', 9, 6;
EXEC create_message_forum 'Iusto accusamus absque celer abbas suadeo terra surculus animus deprimo.', 10, 4;
EXEC create_message_forum 'Adnuo abduco curto alter studio venustas agnitio.', 10, 8;
EXEC create_message_forum 'Harum deficio sequi deputo convoco appello arceo cogito subnecto nemo.', 5, 1;
EXEC create_message_forum 'Coniecto cras capto conatus spargo vado viscus.', 10, 6;
EXEC create_message_forum 'Ater vitium ulciscor molestiae.', 3, 6;
EXEC create_message_forum 'Suspendo cuppedia porro derelinquo vel ait voluptates.', 3, 2;
EXEC create_message_forum 'Eos acidus quis contra tribuo nesciunt.', 5, 7;
EXEC create_message_forum 'Voluptates magni uterque vulgaris quo sapiente defluo sursum virgo vaco.', 4, 10;
EXEC create_message_forum 'Valeo laborum adeo atrox.', 7, 2;
EXEC create_message_forum 'Studio vinco voluptatibus viridis tot pauper inventore vapulus cavus.', 9, 5;
EXEC create_message_forum 'Officia averto inflammatio vergo currus blanditiis aranea tantum dedecor conforto.', 9, 8;
EXEC create_message_forum 'Vesica patruus amplexus absum corporis conservo tonsor decimus.', 6, 4;
EXEC create_message_forum 'Deduco utpote cinis ad deorsum aedificium deserunt stipes utroque.', 4, 3;
EXEC create_message_forum 'Decumbo cupio laudantium tantillus antepono vesica.', 3, 5;
EXEC create_message_forum 'Terra sordeo adulescens clamo vero.', 4, 4;
EXEC create_message_forum 'Commemoro cubitum vos aptus.', 10, 1;
EXEC create_message_forum 'Aranea amiculum coruscus.', 7, 3;
EXEC create_message_forum 'Aiunt anser demulceo autem pel adulescens traho arguo abstergo id.', 1, 10;
EXEC create_message_forum 'Soleo contigo repellat videlicet cauda praesentium vitium.', 7, 5;
EXEC create_message_forum 'Curia volo talus quasi qui adduco textus acerbitas altus.', 10, 2;
EXEC create_message_forum 'Tametsi autus complectus solitudo balbus.', 9, 9;
EXEC create_message_forum 'Studio sufficio denego attollo denuncio.', 3, 5;
EXEC create_message_forum 'Nisi articulus repudiandae patria.', 3, 3;
EXEC create_message_forum 'Apostolus cupressus auxilium.', 4, 4;
EXEC create_message_forum 'Aeternus totam bardus clibanus tredecim laboriosam bibo.', 2, 1;
EXEC create_message_forum 'Cervus cupressus demulceo calamitas suspendo vae comburo.', 10, 9;
EXEC create_message_forum 'Cribro odit vado.', 3, 6;
EXEC create_message_forum 'Allatus viridis adhaero color.', 2, 9;
EXEC create_message_forum 'Dedico aegrotatio adsuesco ambulo clamo suffoco desidero suspendo.', 6, 6;
EXEC create_message_forum 'Amiculum cupressus cetera suscipio solus dolorem acies.', 5, 1;
EXEC create_message_forum 'Copia vae tot.', 2, 5;
EXEC create_message_forum 'Abstergo velit ustulo ullam cubitum avarus ager somniculosus vinco.', 1, 3;
EXEC create_message_forum 'Eius arguo certus.', 7, 8;
EXEC create_message_forum 'Civis vinco animadverto doloremque amplexus facilis fugit.', 10, 6;
EXEC create_message_forum 'Tabgo articulus perspiciatis templum suffragium.', 5, 9;
EXEC create_message_forum 'Rem talis cognatus chirographum alienus depopulo ullam aperte appositus.', 8, 2;
EXEC create_message_forum 'Molestiae colo atavus abeo combibo allatus careo cognomen.', 7, 1;
EXEC create_message_forum 'Repellat in odit suppellex arbitro sed censura ulterius infit.', 8, 8;
EXEC create_message_forum 'Triduana alias atrocitas xiphias ciminatio cultellus omnis demens.', 10, 6;
EXEC create_message_forum 'Depono annus antiquus labore.', 4, 2;
EXEC create_message_forum 'Decumbo dicta adeptio custodia sed confido veritatis vulpes aperte.', 7, 3;
EXEC create_message_forum 'Impedit patruus cogo contigo ancilla ubi.', 7, 2;
EXEC create_message_forum 'Paulatim vestigium arto aliquam vulpes conatus voveo tredecim.', 9, 8;
EXEC create_message_forum 'Creta suffoco amitto.', 7, 4;
EXEC create_message_forum 'Usque conventus cohors.', 5, 4;
EXEC create_message_forum 'Cedo textor aiunt ad viriliter crinis aeternus abbas.', 1, 8;
EXEC create_message_forum 'Ciminatio caput tantum.', 10, 3;
EXEC create_message_forum 'Tempus carmen conitor desino acies credo.', 5, 4;
EXEC create_message_forum 'Tumultus socius congregatio sol speculum pauci vitiosus incidunt placeat caterva.', 3, 9;
EXEC create_message_forum 'Clam civitas una modi atque.', 4, 4;
EXEC create_message_forum 'Traho quod adhaero unde cinis deludo solio.', 4, 3;
EXEC create_message_forum 'Blanditiis basium dolorum blandior cibo videlicet vito aliquid.', 1, 1;
EXEC create_message_forum 'Suppono amissio credo socius circumvenio tracto crebro condico sustineo.', 8, 2;
EXEC create_message_forum 'Paulatim adfero viduo.', 9, 9;
EXEC create_message_forum 'Architecto versus subnecto soleo crudelis cerno.', 10, 5;
EXEC create_message_forum 'Thymum venio curtus iste thymbra communis crux.', 1, 8;
EXEC create_message_forum 'Vergo dicta dolor ademptio pauper urbanus ago tabula curvo voveo.', 3, 8;
EXEC create_message_forum 'Quia verto debitis tabgo.', 6, 8;
EXEC create_message_forum 'Textus tricesimus damno animi curatio.', 10, 6;
EXEC create_message_forum 'Deputo adhaero ara.', 1, 4;
EXEC create_message_forum 'Ante vado trucido audio recusandae talus.', 2, 10;
EXEC create_message_forum 'Curo cognomen spiritus bellum atque.', 6, 4;
EXEC create_message_forum 'Calcar torqueo stabilis acies admiratio corrumpo ater.', 4, 4;
EXEC create_message_forum 'Cariosus deputo debilito ustilo id similique.', 1, 3;
EXEC create_message_forum 'Acervus saepe stella cubicularis audax sulum thymum quibusdam vito.', 5, 8;
EXEC create_message_forum 'Considero callide adhaero adopto arcesso suggero dolores volva degero.', 7, 4;
EXEC create_message_forum 'Omnis surgo civitas dignissimos demens viridis.', 6, 8;
EXEC create_message_forum 'Cauda cogito undique.', 6, 9;
EXEC create_message_forum 'Via uredo sapiente.', 1, 7;
EXEC create_message_forum 'Curvo vigor synagoga amplexus candidus vita.', 7, 9;
EXEC create_message_forum 'Quod nobis depereo demum soleo.', 8, 9;
EXEC create_message_forum 'Causa adulatio verto necessitatibus cupio cotidie summisse arca.', 3, 3;
EXEC create_message_forum 'Caelum conduco dens aveho verumtamen aequitas.', 4, 1;
EXEC create_message_forum 'Clibanus cresco beatus brevis desidero trepide.', 10, 9;
EXEC create_message_forum 'Desidero tonsor bellicus creator attero quaerat qui sumo consuasor colo.', 9, 10;